# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01db0fd9654d91cece1693684f65651c4e5beb75a1abdac204f1985e51a0f243196b8c2ae68234b27ebc3f81e0a0b3bd5e2e59f71cca3c009bc8ac6c4fbfec32

test:
  secret_key_base: 812c66496b34bc21eca5fc5536c60fdddcef6b79a70324659bc4bf56c62e862b71d3245c9269af89c051a6baff81e66f250dc5d08e1973db1c4f156fc25553dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
